"""empty message

Revision ID: 326b628d32d9
Revises: e6e1a0cf6f24
Create Date: 2019-04-27 22:37:38.789955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326b628d32d9'
down_revision = 'e6e1a0cf6f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Unicode(), nullable=False),
    sa.Column('cv_fileid', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cv_fileid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###
